language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq valgrind

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

script: 
  - $CXX --version
  - cd src
  - make debug
  - cd ..
  - ./bin/tarot --debug 3 10
  - ./bin/tarot --debug 4 10
  - ./bin/tarot --debug 5 10
  # - valgrind --leak-check=full --show-reachable=yes bin/tarot --auto
  # - valgrind --tool=cachegrind bin/tarot --auto